// file: src/enums/error-code.enum.ts

export const ErrorCodeEnum = {
  // Authentication Errors
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",

  // Password Reset Errors
  PASSWORD_RESET_TOKEN_INVALID: "PASSWORD_RESET_TOKEN_INVALID",
  PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
  PASSWORD_RESET_CODE_INVALID: "PASSWORD_RESET_CODE_INVALID",
  PASSWORD_RESET_CODE_EXPIRED: "PASSWORD_RESET_CODE_EXPIRED",
  PASSWORD_RESET_REQUEST_NOT_FOUND: "PASSWORD_RESET_REQUEST_NOT_FOUND",

  // Access Control Errors
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // Request Errors
  REQUEST_TOO_LARGE: "REQUEST_TOO_LARGE",
  INVALID_REQUEST_FORMAT: "INVALID_REQUEST_FORMAT",

  // Database Errors
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_VALIDATION_ERROR: "DATABASE_VALIDATION_ERROR",

  // Pagination Errors
  PAGINATION_INVALID_PAGE: "PAGINATION_INVALID_PAGE",
  PAGINATION_INVALID_LIMIT: "PAGINATION_INVALID_LIMIT",
  PAGINATION_PAGE_OUT_OF_RANGE: "PAGINATION_PAGE_OUT_OF_RANGE",
  PAGINATION_LIMIT_EXCEEDED: "PAGINATION_LIMIT_EXCEEDED",
  PAGINATION_INVALID_SORT_FIELD: "PAGINATION_INVALID_SORT_FIELD",
  PAGINATION_TIMEOUT_ERROR: "PAGINATION_TIMEOUT_ERROR",
  PAGINATION_PERFORMANCE_WARNING: "PAGINATION_PERFORMANCE_WARNING",
  PAGINATION_INDEX_MISSING: "PAGINATION_INDEX_MISSING",
  // System Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  //  new
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
