import type { Document, Types } from "mongoose";

import type {
  ACCOUNT_STATUS,
  GENDERS,
  ROLES,
  USER_STATUS,
} from "@/constants/app.constants";

export type IUser = {
  _id: Types.ObjectId;
  email: string;
  passwordHash?: string;
  firebaseUid?: string;
  appleUid?: string;
  authProvider?: "email" | "google" | "apple";
  phoneNumber?: string;
  phone?: string;
  address?: string;
  country?: string;
  state?: string;
  city?: string;
  fullName: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  accountStatus: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];
  status: (typeof USER_STATUS)[keyof typeof USER_STATUS];
  blockedReason?: string;
  blockedAt?: Date;
  blockedBy?: Types.ObjectId;
  dob?: Date;
  gender?: (typeof GENDERS)[keyof typeof GENDERS];
  location?: {
    label?: string;
    coordinates?: {
      type: "Point";
      coordinates: [number, number];
    };
  };
  bio?: string;
  profilePhoto?: Types.ObjectId | null;
  coverPhoto?: Types.ObjectId | null;
  gallery?: Types.ObjectId[];
  creatorStatus?: {
    subscriptionActive?: boolean;
    subscriptionId?: string | null;
  };
  rating?: {
    avg?: number;
    count?: number;
  };
  blockedUsers?: Types.ObjectId[];
  profileImageUrl?: string | null;
  coverImageUrl?: string | null;
  cleanerPercentage?: number;
  emailVerified: boolean;
  emailVerifiedAt?: Date | null;
  emailVerificationToken?: string;
  emailVerificationExpiresAt?: Date;
  lastLoginAt?: Date;
  loginAttempts?: number;
  loginLockedUntil?: Date;
  refreshTokenInvalidBefore?: Date;
  isDeleted?: boolean;
  deletedAt?: Date;
  deletedBy?: Types.ObjectId;
  onboardingCompletedAt?: Date;
  onboardingSkippedAt?: Date;
  stripeAccountId?: string | null;
  stripeCustomerId?: string | null;
  stripeOnboardingCompleted?: boolean;
  stripeDetailsSubmitted?: boolean;
  stripeChargesEnabled?: boolean;
  stripePayoutsEnabled?: boolean;
  stripeDisabledReason?: string | null;
  notificationPreferences?: {
    activityJoined?: boolean;
    activityLeft?: boolean;
    activityUpdated?: boolean;
    activityCancelled?: boolean;
    eventJoined?: boolean;
    eventLeft?: boolean;
    eventUpdated?: boolean;
    eventCancelled?: boolean;
    messages?: boolean;
    reviews?: boolean;
    support?: boolean;
    payouts?: boolean;
    reportStatusUpdated?: boolean;
    reportModeration?: boolean;
    contentReported?: boolean;
    system?: boolean;
  };
  mustChangePassword?: boolean;
  passwordAutoGenerated?: boolean;
  createdAt: Date;
  updatedAt: Date;
} & Document;

/**
 *Password Reset OTP Document Interface
 */
export type IPasswordResetOTP = {
  userId: string;
  otp: string;
  expiresAt: Date;
  attempts: number;
  maxAttempts: number;
  isUsed: boolean;
  usedAt?: Date;
  createdAt: Date;
} & Document;

// 🔑 REFRESH TOKEN BLACKLIST
export type IRefreshTokenBlacklist = {
  userId: Types.ObjectId | string;
  token: string;
  expiresAt: Date;
  reason: "logout" | "password_change" | "security_incident" | "admin_action";
  createdAt: Date;
  updatedAt?: Date;
} & Document;
