// file: src/modules/user/user.model.ts

import { ACCOUNT_STATUS, ROLES } from "@/constants/app.constants";
import { BaseSchemaUtil } from "@/utils/base-schema.utils";
import { model, Query } from "mongoose";
import type { IUser } from "./user.interface";

const userSchema = BaseSchemaUtil.createSchema<IUser>({
  ...BaseSchemaUtil.mergeDefinitions(
    BaseSchemaUtil.emailField(true),
    BaseSchemaUtil.passwordField(),
    BaseSchemaUtil.phoneField(),
    BaseSchemaUtil.softDeleteFields(),
    {
      fullName: {
        type: String,
        required: true,
        trim: true,
        index: true,
      },
      address: {
        type: String,
        required: true,
        trim: true,
      },
      role: {
        type: String,
        enum: Object.values(ROLES),
        required: true,
        index: true,
      },
      accountStatus: {
        type: String,
        enum: Object.values(ACCOUNT_STATUS),
        default: ACCOUNT_STATUS.PENDING,
        index: true,
      },

      profileImageUrl: {
        type: String,
        default: null,
        sparse: true,
        index: true,
      },
      cleanerPercentage: {
        type: Number,
        min: 0,
        max: 100,
      },

      emailVerified: {
        type: Boolean,
        default: false,
        index: true,
      },
      emailVerificationToken: {
        type: String,
        select: false,
      },
      emailVerificationExpiresAt: {
        type: Date,
        select: false,
      },

      lastLoginAt: {
        type: Date,
        index: true,
      },
      passwordChangedAt: {
        type: Date,
      },
      mustChangePassword: {
        type: Boolean,
        default: false,
      },
      passwordAutoGenerated: {
        type: Boolean,
        default: false,
      },
    }
  ),
});

// Existing indexes
userSchema.index({ email: 1, isDeleted: 1 });
userSchema.index({ role: 1, accountStatus: 1, isDeleted: 1 });
userSchema.index({ createdAt: -1, isDeleted: 1 });

userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (!this.getOptions().includeDeleted) {
    this.where({ isDeleted: false });
  }
});

userSchema.set("toJSON", { virtuals: true });
userSchema.set("toObject", { virtuals: true });

import mongoose from "mongoose";

const refreshTokenBlacklistSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    token: {
      type: String,
      required: true,
    },
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 },
    },
    reason: {
      type: String,
      enum: ["logout", "password_change", "security_incident", "admin_action"],
      default: "logout",
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

export const RefreshTokenBlacklist = mongoose.model(
  "RefreshTokenBlacklist",
  refreshTokenBlacklistSchema
);

export const User = model<IUser>("User", userSchema);
