// file: src/modules/user/user.model.ts

import {
  ACCOUNT_STATUS,
  GENDERS,
  ROLES,
  USER_STATUS,
} from "@/constants/app.constants";
import { BaseSchemaUtil } from "@/utils/base-schema.utils";
import { model, Query, Schema } from "mongoose";
import type { IUser } from "./user.interface";

const pointSchema = new Schema(
  {
    type: {
      type: String,
      enum: ["Point"],
      default: "Point",
    },
    coordinates: {
      type: [Number],
      default: undefined,
    },
  },
  { _id: false }
);

const locationSchema = new Schema(
  {
    label: {
      type: String,
      trim: true,
    },
    coordinates: {
      type: pointSchema,
      default: undefined,
    },
  },
  { _id: false }
);

const userSchema = BaseSchemaUtil.createSchema<IUser>({
  ...BaseSchemaUtil.mergeDefinitions(
    BaseSchemaUtil.emailField(true),
    BaseSchemaUtil.passwordField(),
    BaseSchemaUtil.phoneField(),
    BaseSchemaUtil.softDeleteFields(),
    {
      fullName: {
        type: String,
        required: true,
        trim: true,
        index: true,
      },
      phone: {
        type: String,
        trim: true,
      },
      dob: {
        type: Date,
      },
      gender: {
        type: String,
        enum: Object.values(GENDERS),
      },
      address: {
        type: String,
        trim: true,
      },
      role: {
        type: String,
        enum: Object.values(ROLES),
        required: true,
        index: true,
      },
      status: {
        type: String,
        enum: Object.values(USER_STATUS),
        default: USER_STATUS.ACTIVE,
        index: true,
      },
      blockedReason: {
        type: String,
        trim: true,
        maxlength: 500,
      },
      blockedAt: {
        type: Date,
      },
      blockedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
      },
      creatorStatus: {
        subscriptionActive: {
          type: Boolean,
          default: false,
        },
        subscriptionId: {
          type: String,
          default: null,
        },
      },
      rating: {
        avg: {
          type: Number,
          default: 0,
          min: 0,
          max: 5,
        },
        count: {
          type: Number,
          default: 0,
          min: 0,
        },
      },
      location: {
        type: locationSchema,
        default: undefined,
      },
      bio: {
        type: String,
        trim: true,
        maxlength: 1000,
      },
      profilePhoto: {
        type: Schema.Types.ObjectId,
        ref: "Media",
        default: null,
      },
      coverPhoto: {
        type: Schema.Types.ObjectId,
        ref: "Media",
        default: null,
      },
      gallery: [
        {
          type: Schema.Types.ObjectId,
          ref: "Media",
        },
      ],
      blockedUsers: [
        {
          type: Schema.Types.ObjectId,
          ref: "User",
        },
      ],
      accountStatus: {
        type: String,
        enum: Object.values(ACCOUNT_STATUS),
        default: ACCOUNT_STATUS.PENDING,
        index: true,
      },

      profileImageUrl: {
        type: String,
        default: null,
        sparse: true,
        index: true,
      },
      coverImageUrl: {
        type: String,
        default: null,
        sparse: true,
      },
      cleanerPercentage: {
        type: Number,
        min: 0,
        max: 100,
      },

      emailVerified: {
        type: Boolean,
        default: false,
        index: true,
      },
      emailVerifiedAt: {
        type: Date,
      },
      emailVerificationToken: {
        type: String,
        select: false,
      },
      emailVerificationExpiresAt: {
        type: Date,
        select: false,
      },

      lastLoginAt: {
        type: Date,
        index: true,
      },
      loginAttempts: {
        type: Number,
        default: 0,
      },
      loginLockedUntil: {
        type: Date,
      },
      refreshTokenInvalidBefore: {
        type: Date,
      },
      onboardingCompletedAt: {
        type: Date,
      },
      onboardingSkippedAt: {
        type: Date,
      },
      stripeAccountId: {
        type: String,
        trim: true,
        sparse: true,
        index: true,
      },
      stripeCustomerId: {
        type: String,
        trim: true,
        sparse: true,
        index: true,
      },
      stripeOnboardingCompleted: {
        type: Boolean,
        default: false,
        index: true,
      },
      passwordChangedAt: {
        type: Date,
      },
      mustChangePassword: {
        type: Boolean,
        default: false,
      },
      passwordAutoGenerated: {
        type: Boolean,
        default: false,
      },
    }
  ),
});

// Existing indexes
userSchema.index({ email: 1, isDeleted: 1 });
userSchema.index({ role: 1, accountStatus: 1, isDeleted: 1 });
userSchema.index({ createdAt: -1, isDeleted: 1 });
userSchema.index({ status: 1, role: 1 });
userSchema.index({ status: 1, isDeleted: 1, createdAt: -1 });
userSchema.index({ role: 1, status: 1, isDeleted: 1, createdAt: -1 });
userSchema.index({ "location.coordinates": "2dsphere" });

userSchema.pre(/^find/, function (this: Query<any, IUser>) {
  if (!this.getOptions().includeDeleted) {
    this.where({ isDeleted: false });
  }
});

userSchema.set("toJSON", { virtuals: true });
userSchema.set("toObject", { virtuals: true });

import mongoose from "mongoose";

const refreshTokenBlacklistSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    token: {
      type: String,
      required: true,
    },
    expiresAt: {
      type: Date,
      required: true,
      index: { expireAfterSeconds: 0 },
    },
    reason: {
      type: String,
      enum: ["logout", "password_change", "security_incident", "admin_action"],
      default: "logout",
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

export const RefreshTokenBlacklist = mongoose.model(
  "RefreshTokenBlacklist",
  refreshTokenBlacklistSchema
);

export const User = model<IUser>("User", userSchema);
