import { ACCOUNT_STATUS, ROLES } from "@/constants/app.constants";
import type { Document, Types } from "mongoose";

export interface IUser extends Document {
  _id: Types.ObjectId;
  email: string;
  password?: string;
  phoneNumber?: string;
  address: string;
  fullName: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  accountStatus: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];
  profileImageUrl?: string | null;
  cleanerPercentage?: number;
  emailVerified: boolean;
  emailVerificationToken?: string;
  emailVerificationExpiresAt?: Date;
  lastLoginAt?: Date;
  mustChangePassword?: boolean;
  passwordAutoGenerated?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 *Password Reset OTP Document Interface
 */
export interface IPasswordResetOTP extends Document {
  userId: string;
  otp: string;
  expiresAt: Date;
  attempts: number;
  maxAttempts: number;
  isUsed: boolean;
  usedAt?: Date;
  createdAt: Date;
}

// 🔑 REFRESH TOKEN BLACKLIST
export interface IRefreshTokenBlacklist extends Document {
  userId: Types.ObjectId | string;
  token: string;
  expiresAt: Date;
  reason: "logout" | "password_change" | "security_incident" | "admin_action";
  createdAt: Date;
  updatedAt?: Date;
}
